### ISSUE TITLE
Package ‘datastructures’ was removed from the CRAN repository.

### ISSUE THREAD

**Issue by Marc-Ruebsam** [dirmeier/datastructures#18]
> Package ‘datastructures’ was removed from the CRAN repository.
> Formerly available versions can be obtained from the [archive](https://cran.r-project.org/src/contrib/Archive/datastructures).
> Archived on 2023-05-05 as issues were not corrected in time.
> A summary of the most recent check results can be obtained from the [check results archive](https://cran-archive.r-project.org/web/checks/2023/2023-05-05_check_results_datastructures.html).
> Please use the canonical form https://cran.r-project.org/package=datastructures to link to this page.

Will datastructures return to CRAN any time soon?

**Comment by dirmeier** [comment]
Hey, 
Thanks for opening up an issue. I wasn't aware that it got removed. I don't have much time on my hands to add this again to CRAN, and seeing that the package doesn't really get used (i.e., cited) I don't think I will try to find it. 

Fixes in the form of PRs are welcome though.

Cheers,
S
