### ISSUE TITLE
Insert a list of values under a key in heap

### ISSUE THREAD

**Issue by yushuf** [dirmeier/datastructures#2]
Hi,
The package is a nice contribution. I am using this for an epidemic simulation. I am having a trouble using heap.

You heap structure take only key and value as argument. But frequently we need to insert a key with a value as list like 
fheap <- fibonacci_heap("numeric", c("integer", "integer")). That means values length will be 1 or more. This improvement could help the package user so much. Also this package will be then a competitor with Python heapq package.

I hope to see the update in future.

Again thanks for producing such an helpful package

Yushuf

**Comment by dirmeier** [comment]
Hey Yushuf, yeah that makes sense. I'll do that asap. 
This week is a little busy though. 

Thanks! Nice to that the package is useful to you :)

**Comment by dirmeier** [comment]
Hey Yushuf, 

the latest [CRAN](https://cran.r-project.org/web/packages/datastructures/index.html) release fixes this. Have fun!

Please close the issue, if it it's working for you now/
