### ISSUE TITLE
remove an element from a hashmap

### ISSUE THREAD

**Issue by kvak** [dirmeier/datastructures#7]
Consider this example:
```

hm <- hashmap("integer")
keys <- 1:2
values <- list(
  3L,
  data.frame(A=rbeta(3, .5, .5), B=rgamma(3, 1)))
hm[keys] <- values

```

how can I remove the element `hm[1L]`?

**Comment by dirmeier** [comment]
Hey, this unfortunately doesn't work and is a known bug (https://github.com/dirmeier/datastructures/issues/6). I'll fix this tomo and add some utility functions, too. Thanks!

**Comment by dirmeier** [comment]
Hey, the latest commit https://github.com/dirmeier/datastructures/commit/d4aa98874b988067674ffccf3f3a2e9ecba7d89e fixes this. 
Would be nice if you could test it, otherwise I submit to CRAN in two or three days.

Just install with
```{r}
devtools::install_github("dirmeier/datastructures")
```
