### ISSUE TITLE
`dequer` seems like relevant prior work in a very similar direction

### ISSUE THREAD

**Issue by fabian-s** [dirmeier/datastructures#9]
IIUC, JOSS would like to see you mention relevant prior work that is similar, 
so please mention/compare https://github.com/wrathematics/dequer

openjournals/joss-reviews#907

**Comment by dirmeier** [comment]
Added `dequer` and `hashmap` as references to the paper. DO you know whether there's a way to rebuild the document?

**Comment by fabian-s** [comment]
The way I read the guidelines, the bot is looking for a `paper.md` file in your repo (but maybe not in a subdirectory of your repo...?) I just tried to get their bot to re-generate the paper, let's see...
